import Link from "next/link";
import React from "react";

function AboutSolarFinance() {
  const typesOfSolarFinancing = [
    {
      heading: "Solar Loans",
      text: "These are traditional loans specifically designed for financing solar energy projects. Borrowers can use the loan to cover the upfront costs of purchasing and installing solar panels, and then repay the loan over time with interest.",
    },
    {
      heading: "Solar Leases",
      text: "With a solar lease, the solar energy system is owned by a third-party provider who installs and maintains the system on the customer's property. The customer pays a monthly lease payment for the use of the system and typically benefits from lower electricity bills.",
    },
    {
      heading: "Power Purchase Agreements (PPAs)",
      text: "PPAs are contracts between a solar provider and a property owner, where the provider installs and maintains the solar panels on the property at no upfront cost to the owner. In return, the property owner agrees to purchase the electricity generated by the system at a predetermined rate for a specified period, often 10-20 years.",
    },
    {
      heading: "Property-Assessed Clean Energy (PACE) Financing",
      text: "PACE financing allows property owners to finance energy efficiency and renewable energy upgrades, including solar installations, through a special assessment added to their property tax bill. PACE financing programs vary by location and may offer favorable terms such as longer repayment periods and fixed interest rates.",
    },
  ];

  return (
    <>
      <div className="px-4 mb-4 text-center md:mb-8 mt-24">
        <p className="mb-2 text-base md:text-lg font-semibold font-sans text-teal-500 ">
          Solar Financing
        </p>
        <h2 className="pb-2 text-2xl font-sans font-semibold text-slate-800 md:text-5xl ">
          What Is Solar Financing?
        </h2>
        <div className="flex w-72 mt-1 md:mt-3 mb-6 overflow-hidden rounded   mx-auto md:mb-8">
          <div className="flex-1 h-2 bg-teal-200"></div>
          <div className="flex-1 h-2 bg-teal-400"></div>
          <div className="flex-1 h-2 bg-teal-300"></div>
        </div>
      </div>
      <section className="text-teal-800 font-sans italic body-font mb-6">
        <div className="container px-5 mt-2 mx-auto">
          <div className="xl:w-[67%]  w-full mx-auto text-center">
            <p className="leading-relaxed text-lg">
              Solar financing refers to the various methods and mechanisms
              through which individuals, businesses, or organizations can fund
              the installation of solar energy systems. Since solar panel
              systems can involve significant upfront costs, financing options
              are available to help make them more affordable and accessible to
              a wider range of consumers.
            </p>
          </div>
        </div>
      </section>
      <div className="px-4 mb-4 text-center  mt-5">
        <h2 className=" text-xl font-sans font-semibold text-slate-800 md:text-3xl ">
          Common Forms of Solar Financing
        </h2>
        <span className="inline-block h-[.18rem] w-44 rounded bg-teal-500 mb-2" />
      </div>

      <div className=" grid md:grid-cols-2 gap-4 justify-center items-center xl:px-20 px-2">
        {typesOfSolarFinancing.map((item,i)=><div key={i} className=" p-6 h-fit lg:h-[15rem]  bg-[#d6f8e7]  hover:bg-[#c0fada] border border-gray-200 rounded-lg shadow ">
          <h5 className="mb-2 font-sans text-2xl font-semibold tracking-tight text-gray-700 ">
            {item.heading}
          </h5>
          <p className="font-normal font-sans text-gray-600 ">
            {item.text}
          </p>
        </div>)}

        
      </div>
      
    </>
  );
}

export default AboutSolarFinance;
